import type { Metadata, Viewport } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import Providers from "./components/providers";
import ProvidersLayout from "./components/ProvidersLayout";

const lexend = Lexend({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "WeWIN",
  description: "Generated by WeWIN Education",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${lexend.className} antialiased bg-pink-50 flex flex-col min-h-screen`}
      >
        {/* ✅ Wrap toàn app trong SessionProvider */}
        <Providers>
          <ProvidersLayout>{children}</ProvidersLayout>
        </Providers>
      </body>
    </html>
  );
}
