// 🧭 Enum định nghĩa các route chính của hệ thống
export const Routes = {
  HOME: "/",
  TEST_IELTS: "/test/ielts",
  RESOURCES: "/resources",
  RESOURCES_KIDS: "/resources/kids",
  RESOURCES_STARTERS_FOUNDATION: "/resources/starters-foundation",
  RESOURCES_STARTERS: "/resources/starters",
  RESOURCES_MOVERS: "/resources/movers",
  RESOURCES_FLYERS: "/resources/flyers",
  RESOURCES_AUDIO: "/resources/audio",
  RESOURCES_VIDEO: "/resources/video",
  RESOURCES_GAMES: "/games",
  RESOURCES_GAMES_KIDS: "/resources/kids/Games",
  RESOURCES_GAMES_STARTERS: "/resources/starters/Games",
  RESOURCES_GAMES_MOVERS: "/resources/mover/Games",
  RESOURCES_GAMES_FLYERS: "/resources/flyer/Games",
  MANAGE_CLASS: "/class",
  MANAGE_CLASS_DETAIL: (id: string) => `/class/${id}`,
  MANAGE_CLASS_CATEGORY: "/class/category",
  MANAGE_STUDENT: "/student",
  MANAGE_STORAGE: "/storage",
  MANAGE_STORAGE_LIST: "/storage/list",
  MANAGE_STORAGE_DETAIL: (id: string) => `/storage/list/${id}`,
  MANAGE_STORAGE_REQUEST: "/storage/request",
  MANAGE_STORAGE_REQUEST_DETAIL: (id: string) => `/storage/request/${id}`,
  MANAGE_STORAGE_HISTORY: "/storage/history",
} as const;
